name: Release Fresh Docker Image

on: workflow_dispatch

jobs:
    release_dependency_image:
        name: Release Image with Dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ env.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build Docker image
              run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/voil-ci:adae ./docker
            - name: Push image to DockerHub
              run: docker push ${{ env.DOCKERHUB_USERNAME }}/voil-ci:adae
